// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using SimpleSCADA_Controller;

#nullable disable

namespace SimpleSCADA_SharedResources.Migrations
{
    [DbContext(typeof(RecipeManager))]
    [Migration("20230601124934_InitialCreate1")]
    partial class InitialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RecipeStation", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipesId", "StationsId");

                    b.HasIndex("StationsId");

                    b.ToTable("RecipeStation");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductionCycleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Starttime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionCycleId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.ProductionCycle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedTime")
                        .HasColumnType("REAL");

                    b.Property<int>("FinishedProducts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("ProductionCycle");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilities");
                });

            modelBuilder.Entity("StationUtility", b =>
                {
                    b.Property<int>("StationsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilitiesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StationsId", "UtilitiesId");

                    b.HasIndex("UtilitiesId");

                    b.ToTable("StationUtility");
                });

            modelBuilder.Entity("RecipeStation", b =>
                {
                    b.HasOne("SimpleSCADA_SharedResources.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleSCADA_SharedResources.Station", null)
                        .WithMany()
                        .HasForeignKey("StationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.Log", b =>
                {
                    b.HasOne("SimpleSCADA_SharedResources.ProductionCycle", "ProductionCycle")
                        .WithMany("Logs")
                        .HasForeignKey("ProductionCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionCycle");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.ProductionCycle", b =>
                {
                    b.HasOne("SimpleSCADA_SharedResources.Recipe", "Recipe")
                        .WithMany("ProductionCycles")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("StationUtility", b =>
                {
                    b.HasOne("SimpleSCADA_SharedResources.Station", null)
                        .WithMany()
                        .HasForeignKey("StationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleSCADA_SharedResources.Utility", null)
                        .WithMany()
                        .HasForeignKey("UtilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.ProductionCycle", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SimpleSCADA_SharedResources.Recipe", b =>
                {
                    b.Navigation("ProductionCycles");
                });
#pragma warning restore 612, 618
        }
    }
}
